return PlaceObj('ModDef', {
	'title', "Rusty_Wash",
	'description', "Working at the car wash,\nWorking at the car wash, yeah,\nCome on and sing it with me, car wash,\nSing it with the feeling now, car wash, yeah...\n\nRustyWash; a building mainly just for fun... \n\nCosts;\n20 Concrete\n15 Metal\n1 Electronic\n1 Polymer\n\nMaintenance;\n1 Metal\n\nAutomatically cleans units within the dome, park a unit on the blue Hex to place it within the dome. Eject a unit using the infopanel button. \n\nDOES NOT function during dust storms - too much dust.\nWill automatically stop using water if no unit is inside.\nWhilst working you can optionally spray paint units in new colours.\nThis only affects visuals, not maintenance points. Cleans/paints Rovers and drones.\n\nFixes; Mod contains an override for drones that are painted to remain in the colour, normal game behaviour reverts the colours on idle. \n\nSpecial Thanks to;\nChoGGi for the original inspiration and base code work, see his mod here;\n https://steamcommunity.com/sharedfiles/filedetails/?id=1411110474 \n\nSilva for allowing me to use and adapt a model he created for his Forest Greenhouse mod;\n https://steamcommunity.com/sharedfiles/filedetails/?id=1627181550 \n\nEnjoy !!",
	'image', "thumbnail.png",
	'last_changes', "v2 Fixed up some issues with selection/sounds",
	'ignore_files', {
		"*.git/*",
		"*.svn/*",
		"*preview*",
	},
	'id', "aCufZJe",
	'steam_id', "1785246205",
	'pops_desktop_uuid', "e336a2ed-3771-4fc6-8d89-cf8ed9b50119",
	'pops_any_uuid', "b91d670b-0a3b-42c4-8cee-3ed36014c858",
	'author', "RustyDios",
	'version_major', 2,
	'version_minor', 1,
	'version', 14,
	'lua_revision', 233360,
	'saved_with_revision', 245618,
	'code', {
		"Code/AddEntities.lua",
		"Code/Script.lua",
		"Code/DroneColorOverride.lua",
	},
	'saved', 1562378185,
	'screenshot1', "thumbnail.png",
	'screenshot2', "preview.png",
	'screenshot3', "preview2.png",
	'TagGameplay', true,
	'TagBuildings', true,
	'TagCosmetics', true,
	'TagOther', true,
})